spring.application.name=web.api
server.port=8081


# Port du serveur
Tomcat started on port(s): 9070 (http)

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque_db
spring.datasource.username=bibliouser
spring.datasource.password=bibliopass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
